spring:

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/workspace_booking}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: ${SPRING_JPA_SHOW_SQL:false}
    show-sql: ${SPRING_JPA_SHOW_SQL:false}

app:
  jwt:
    access-secret: ${APP_JWT_ACCESS_SECRET}
    refresh-secret: ${APP_JWT_REFRESH_SECRET}
    access-expiration-minutes: ${APP_JWT_ACCESS_EXPIRATION_MINUTES:120}
    refresh-expiration-days: ${APP_JWT_REFRESH_EXPIRATION_DAYS:14}
  admin:
    email: ${ADMIN_EMAIL}
    password: ${ADMIN_PASSWORD}
    first-name: ${ADMIN_FIRST_NAME:System}
    last-name: ${ADMIN_LAST_NAME:Administrator}



logging:
  level:
    com.plsrflttr: ${LOG_LEVEL:INFO}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: always
    include-binding-errors: always

